### ISSUE TITLE
Swift-Lite is not compatible with POO with files separated? 

### ISSUE THREAD

**Issue by JosepEscobar** [futurejones/Swift-Lite#2]
I'm trying to create a class in my first test project with `Swift-Lite but` swift-lite-build do not recognize it.

This build its only for procedural language and small scripts? 
(My files are in the same directory)

Testo.swift
``` Swift
import Foundation

class Testo {
    func testFunc() {
        hello()
    }
}
````

main.swift
```Swift 
let main = Testo()
main.testFunc()
```

My output: 

``` Bash
./build/main.swift:12:12: error: use of unresolved identifier 'Testo'
let main = Testo()
           ^~~~~
Build Failed
```

Edit:
I can put my Testo class in Modules directory and i can import as Module and works but then is shared for all projects... Do you have other solution to organize my code on more than one file?

Thanks for your job!

**Comment by futurejones** [comment]
`swift-lite-build` is a convenient build build utility that is meant to be used with a `swiftProject` and `swiftModule` directory structure.
`Swift-Lite` contains all of the the `Swift-Core` components so you can use the standard `swift` compiler to build your project.

To create and build a multi-file project without using `swift-lite-build` you will need to use the `swiftc` command.
For ease of use all files should be contained in a directory called `Source` within the project directory and there must be a `main.swift` file.

Example:
```
mkdir NewProject
cd NewProject
mkdir Source
```
Create your project files and place them in the `Source` directory.

main.swift
```
let main = Testo()
main.testFunc()
```
Testo.swift
```
import Foundation

class Testo {
    func testFunc() {
        hello()
    }
}

func hello() {
    print("Hello World")
}
```
To build a project using `swiftc` all files required by the project must be listed in the build command with the full path to the files. As we have placed all the files in the `Source` directory we can use the following simple command to build all `.swift` files contained in `Source`.
```
swiftc Source/*.swift
```
This will create an `executable` file called `main`. You can run the project with the following command.
```
./main
Hello World
```

**Comment by JosepEscobar** [comment]
Thanks for your response, i can compile now. Im using this project structure (for test): 

```
├── main.swift
├── Sources
│   └── Testo.swift
```
And I have compiled with this command: 

`swiftc main.swift Sources/*.swift`

Like you said, including all .swift files with swift.c
Thanks for all!
